# Generated by Django 3.2.5 on 2021-07-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='texPrice',
            new_name='taxPrice',
        ),
    ]
